sudo: required
services:
- docker
language: go
go:
- 1.8
- tip
go_import_path: github.com/bivas/rivi
install: true
script:
- go list ./... | grep -v vendor | xargs go test -v
- go build
env:
  global:
  - VERSION=$(echo $TRAVIS_TAG)
before_deploy:
- GOOS=linux  GOARCH=amd64 go build -o rivi-${VERSION}-linux-amd64
- GOOS=darwin GOARCH=amd64 go build -o rivi-${VERSION}-darwin-amd64
- GOOS=windows GOARCH=amd64 go build -o rivi-${VERSION}-windows-amd64
deploy:
  provider: releases
  api_key:
    secure: awpl9niknI0uPR7hf8UuZqPNaY53AzhxVGBEQ05sn5HCxAtELHz874HjwOorI2kOxSaUSNnTpRLaRtTloAhGFjoYVWOpo0NlnpbSlu7qVZdi7dtRFb2mEttcmZcV+6gu6Wv0eZQHKrhtKIPdFe9J5dcb135iH7g7YFdiTOGVUIrzuun8WU6wfylGwMX4Ipzh+zD5W76PeFanP4C2gTN7Tu/Sn7SKkgFrV4t08+0FuTnmxu8GLnnT0GqlIDHYeitRRfctwXOO+WiAKJnFK/4IIJqCck/dAVsAQFcqM5pdWkWrbwQZr37aZm9aSYEFFm2AYlo6xg9mUDZqLefm2OFs5E+x89N15nKSH9NCerGzoXZ/YXDJl/OcS4SJfCzQN8LwOU+sxl3CSKWzA6vV46jJaxp327JeIaIVqTV8nKStmaUnY1gRz0xoQn98yDApkcLUtvp4rH+wE/p+XSeMwURpx6YWcvvagKaymoUuLeJtjSAaAEy733maiu/qs7lLhD3drxQjohefyNNHoI971T8Gix7Tsutuzon7V1SZEs7UM8mgCO/KPF1x3EhkwEePEVUYNjH+1tZZoz/yF6dsHmLV5x2HVO93ncfaQ6AvydbmwtOpMPLFrFwrXG3K2FRPyZ7CHUppckpvB53wCQEZNeacWEt1JbjlsVhFys6aFremrjk=
  file:
  - rivi-$VERSION-darwin-amd64
  - rivi-$VERSION-linux-amd64
  - rivi-$VERSION-windows-amd64
  skip_cleanup: true
  on:
    tags: true
